import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/expense_models.dart';
import '../utils/indian_number_format.dart';

/// Generates the ITR Tax Summary PDF for a financial year and returns the saved
/// file (in the temp dir, ready to share). Uses "Rs." rather than the ₹ glyph,
/// which the built-in PDF fonts don't include.
class TaxSummaryPdf {
  const TaxSummaryPdf._();

  static String _rs(double v) => 'Rs. ${indianGroup(v.round())}';

  static Future<File> generate(TaxSummary s, {DateTime? generatedAt}) async {
    final now = generatedAt ?? DateTime.now();
    final doc = pw.Document();

    const green = PdfColor.fromInt(0xFF00A86B);
    const dark = PdfColor.fromInt(0xFF0F172A);
    const muted = PdfColor.fromInt(0xFF64748B);

    pw.Widget row(String label, String value, {bool bold = false}) => pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 7),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(label,
                  style: pw.TextStyle(
                      fontSize: 12,
                      color: dark,
                      fontWeight:
                          bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
              pw.Text(value,
                  style: pw.TextStyle(
                      fontSize: 12,
                      color: dark,
                      fontWeight: pw.FontWeight.bold)),
            ],
          ),
        );

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('INO — Tax Summary',
                style: pw.TextStyle(
                    fontSize: 22, fontWeight: pw.FontWeight.bold, color: green)),
            pw.SizedBox(height: 2),
            pw.Text('Financial Year ${s.year.label}  '
                '(1 Apr ${s.year.startYear} – 31 Mar ${s.year.startYear + 1})',
                style: pw.TextStyle(fontSize: 12, color: muted)),
            pw.SizedBox(height: 20),
            pw.Container(
              padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 6),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColor.fromInt(0xFFE2E8F0)),
                borderRadius: pw.BorderRadius.circular(10),
              ),
              child: pw.Column(
                children: [
                  row('Total Income', _rs(s.totalIncome)),
                  pw.Divider(color: PdfColor.fromInt(0xFFE2E8F0), height: 1),
                  row('Total Expenses', _rs(s.totalExpenses)),
                  pw.Divider(color: PdfColor.fromInt(0xFFE2E8F0), height: 1),
                  row('Total Investments', _rs(s.totalInvestments)),
                  pw.Divider(color: PdfColor.fromInt(0xFFE2E8F0), height: 1),
                  row('Insurance Premiums', _rs(s.insurancePremiums)),
                  pw.Divider(color: PdfColor.fromInt(0xFFE2E8F0), height: 1),
                  row('Medical Expenses', _rs(s.medicalExpenses)),
                  pw.Divider(color: PdfColor.fromInt(0xFFE2E8F0), height: 1),
                  row('Rent Paid', _rs(s.rentPaid)),
                  pw.Divider(color: PdfColor.fromInt(0xFFE2E8F0), height: 1),
                  row('Tax Paid', _rs(s.taxPaid)),
                ],
              ),
            ),
            pw.SizedBox(height: 14),
            pw.Text('${s.transactionCount} transactions on record for this year.',
                style: pw.TextStyle(fontSize: 11, color: muted)),
            pw.Spacer(),
            pw.Divider(color: PdfColor.fromInt(0xFFE2E8F0)),
            pw.Text(
                'Generated by INO on ${now.day}/${now.month}/${now.year}. '
                'This is a personal record summary for reference while preparing '
                'your ITR — it is not a certified tax document.',
                style: pw.TextStyle(fontSize: 9, color: muted)),
          ],
        ),
      ),
    );

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/INO_Tax_Summary_${s.year.label}.pdf');
    await file.writeAsBytes(await doc.save());
    return file;
  }
}
