import 'dart:convert';
import 'dart:developer' as developer;

import 'package:flutter/foundation.dart' show ValueNotifier;
import 'package:http/http.dart' as http;
import 'package:supabase_flutter/supabase_flutter.dart';

import '../config/share_config.dart';
import '../core/net/net_guard.dart';
import '../models/document_share.dart' show ShareDuration, ShareDurationX;
import '../models/view_once_share.dart';
import 'share_repository.dart' show ShareException, ShareBackendNotConfiguredException;

/// The ONLY place in the app that reads/writes `view_once_shares`.
///
/// Mirrors [ShareRepository]'s design - a singleton over `Supabase.instance`
/// with RLS scoping every query to the signed-in owner - but for ONE-TIME links:
/// the recipient may open the document exactly once, after which the link is
/// permanently dead.
///
/// Split of responsibility, deliberately:
///   • **Sender side** ([create], [listMine], [revoke]) goes through Supabase
///     with the owner's session. Creation uses the `create_view_once_share` RPC,
///     which verifies server-side that the document belongs to the caller.
///   • **Recipient side** ([peek], [claim], [fetchFile]) never touches the table.
///     It talks to the anonymous `share` Edge Function over plain HTTP, exactly
///     like the existing public share flow - recipients have no Supabase
///     session, and the one-time gate lives in Postgres where it can be atomic.
///
/// Nothing here duplicates a file: a one-time link points at an existing
/// `documents` row, and the bytes are streamed through the Edge Function.
class ViewOnceRepository {
  ViewOnceRepository._();
  static final ViewOnceRepository instance = ViewOnceRepository._();

  SupabaseClient get _client => Supabase.instance.client;

  static const String _table = 'view_once_shares';

  String? get _uid => _client.auth.currentUser?.id;

  /// Bumped whenever a one-time link is created or revoked, so an open list can
  /// refresh without polling. Same contract as [ShareRepository.revision].
  static final ValueNotifier<int> revision = ValueNotifier<int>(0);
  static void _bump() => revision.value++;

  // ---- Sender side ---------------------------------------------------------

  /// Mints a one-time link for [documentId] that also lapses after [duration]
  /// if nobody opens it.
  ///
  /// The token is generated by Postgres, never by the client, so it can't be
  /// forged or predicted. Throws [ShareException] on rejection and
  /// [ShareBackendNotConfiguredException] when the migration hasn't been
  /// deployed yet.
  Future<ViewOnceShare> create({
    required String documentId,
    required ShareDuration duration,
    ViewDuration viewDuration = ViewDuration.thirtySeconds,
  }) async {
    if (_client.auth.currentUser == null) {
      throw const ShareException('You must be signed in to share documents.');
    }
    if (documentId.isEmpty) {
      throw const ShareException('Select a document to share.');
    }

    final payload = <String, dynamic>{
      'p_document_id': documentId,
      'p_ttl_seconds': duration.seconds,
      'p_view_seconds': viewDuration.seconds,
    };
    developer.log(
      'RPC create_view_once_share → documentId=$documentId '
      'ttl=${duration.seconds}s view=${viewDuration.seconds}s',
      name: 'view-once',
    );

    try {
      final row = await _client
          .rpc('create_view_once_share', params: payload)
          .timeout(NetGuard.mutation);
      final map = (row is List ? (row.isEmpty ? null : row.first) : row)
          as Map<String, dynamic>?;
      if (map == null) {
        throw const ShareException(
            'The server did not return a link. Please try again.');
      }
      final share = ViewOnceShare.fromMap(map);
      developer.log(
        'create_view_once_share OK → url=${share.url} '
        'expires=${share.expiryTime.toIso8601String()}',
        name: 'view-once',
      );
      _bump();
      return share;
    } on PostgrestException catch (e, st) {
      developer.log(
        'create_view_once_share FAILED → code=${e.code} message="${e.message}"',
        name: 'view-once',
        error: e,
        stackTrace: st,
      );
      if (_isMissingBackend(e)) throw ShareBackendNotConfiguredException(e);
      // Preserve the exact Postgres message ("That document is not yours to
      // share", "Invalid expiry duration").
      throw ShareException(e.message, cause: e);
    } on AuthException catch (e) {
      throw ShareException(e.message, cause: e);
    } catch (e) {
      if (e is ShareException) rethrow;
      throw ShareException('Could not create the one-time link. Please try again.',
          cause: e);
    }
  }

  /// Every one-time link the signed-in user has created, newest first.
  Future<List<ViewOnceShare>> listMine({String? documentId}) async {
    final uid = _uid;
    if (uid == null) return const [];
    try {
      var query = _client
          .from(_table)
          .select()
          .eq('owner_id', uid); // defense-in-depth with the owner RLS policy
      if (documentId != null) query = query.eq('document_id', documentId);
      final rows = await query
          .order('created_at', ascending: false)
          .limit(NetGuard.maxRows)
          .timeout(NetGuard.query);
      return [for (final r in rows) ViewOnceShare.fromMap(r)];
    } on PostgrestException catch (e) {
      if (_isMissingBackend(e)) return const [];
      rethrow;
    }
  }

  /// Re-reads one link, so the sender can see whether it has been opened yet.
  Future<ViewOnceShare?> fetch(String token) async {
    final uid = _uid;
    if (uid == null) return null;
    final row = await _client
        .from(_table)
        .select()
        .eq('token', token)
        .eq('owner_id', uid)
        .maybeSingle()
        .timeout(NetGuard.query);
    return row == null ? null : ViewOnceShare.fromMap(row);
  }

  /// Kills a one-time link before anyone opens it. RLS ensures a user can only
  /// revoke their own. (Revoking an already-viewed link is a no-op - it is
  /// already dead.)
  Future<void> revoke(String token) async {
    final uid = _uid;
    if (uid == null) {
      throw const ShareException('You must be signed in to revoke a link.');
    }
    try {
      await _client
          .from(_table)
          .update({'revoked': true})
          .eq('token', token)
          .eq('owner_id', uid)
          .timeout(NetGuard.mutation);
      developer.log('revoke OK → token=${_short(token)}', name: 'view-once');
      _bump();
    } on PostgrestException catch (e) {
      throw ShareException(e.message, cause: e);
    }
  }

  // ---- Recipient side ------------------------------------------------------
  // These hit the anonymous `share` Edge Function over plain HTTP. The private
  // table is never queried directly, and the storage path never leaves Supabase.

  /// NON-CONSUMING status check.
  ///
  /// Safe to call on every screen build: it tells the viewer whether a view is
  /// still available WITHOUT spending it. Only [claim] burns the link. Never
  /// throws - a network failure resolves to [ViewOncePeek.errored].
  Future<ViewOncePeek> peek(String token) async {
    final uri = Uri.parse('${ShareConfig.viewOnceApiUrl(token)}?format=json');
    developer.log('peek → GET $uri', name: 'view-once');
    try {
      final res = await http
          .get(uri, headers: const {'accept': 'application/json'})
          .timeout(const Duration(seconds: 20));
      developer.log('peek ← ${res.statusCode}', name: 'view-once');
      final decoded = jsonDecode(res.body);
      if (decoded is! Map<String, dynamic>) return ViewOncePeek.errored;
      return ViewOncePeek.fromJson(decoded);
    } catch (e, st) {
      developer.log('peek failed: $e',
          name: 'view-once', error: e, stackTrace: st);
      return ViewOncePeek.errored;
    }
  }

  /// BURNS the link and returns the grant needed to read the document.
  ///
  /// Call this exactly once, from an explicit user action - never from
  /// `initState`, a retry loop, or anything a crawler could trigger. The server
  /// flips `viewed` in a single atomic UPDATE, so concurrent opens can never
  /// both succeed; the loser gets [ViewOnceStatus.viewed].
  Future<ViewOnceResult> claim(String token) async {
    final uri = Uri.parse('${ShareConfig.viewOnceApiUrl(token)}/claim');
    developer.log('claim → POST $uri', name: 'view-once');
    try {
      final res = await http
          .post(uri, headers: const {'accept': 'application/json'})
          .timeout(const Duration(seconds: 30));
      developer.log('claim ← ${res.statusCode}', name: 'view-once');
      final decoded = jsonDecode(res.body);
      if (decoded is! Map<String, dynamic>) {
        return const ViewOnceResult.denied(ViewOnceStatus.error);
      }
      if (decoded['status'] == 'claimed') {
        return ViewOnceResult.claimed(ViewOnceClaim.fromJson(decoded));
      }
      return ViewOnceResult.denied(
        viewOnceStatusFrom(decoded['status'] as String?),
        message: decoded['message'] as String?,
      );
    } catch (e, st) {
      developer.log('claim failed: $e',
          name: 'view-once', error: e, stackTrace: st);
      // Ambiguous: the claim may or may not have landed. Report it as an error
      // (retryable) rather than pretending the link is spent.
      return const ViewOnceResult.denied(ViewOnceStatus.error);
    }
  }

  /// Streams the claimed document's bytes through the Edge Function proxy, using
  /// the short-lived [ViewOnceClaim.accessKey]. The bytes stay in memory - a
  /// view-once document is never written to disk by this method.
  ///
  /// Throws [ShareException] on any non-200 response.
  Future<ViewOnceFile> fetchFile(String token, ViewOnceClaim claim) async {
    final uri = Uri.parse(
      '${ShareConfig.viewOnceApiUrl(token)}/file'
      '?k=${Uri.encodeQueryComponent(claim.accessKey)}',
    );
    developer.log('fetchFile → GET ${ShareConfig.viewOnceApiUrl(token)}/file',
        name: 'view-once');
    final res = await http.get(uri).timeout(const Duration(seconds: 60));
    developer.log(
      'fetchFile ← ${res.statusCode} bytes=${res.bodyBytes.length}',
      name: 'view-once',
    );
    if (res.statusCode != 200) {
      String message = 'This one-time view has ended.';
      try {
        final body = jsonDecode(res.body);
        if (body is Map && body['message'] is String) {
          message = body['message'] as String;
        }
      } catch (_) {/* non-JSON body - keep the default */}
      throw ShareException(message);
    }
    final mime = (res.headers['content-type'] ?? claim.mime).split(';').first.trim();
    return ViewOnceFile(
      bytes: res.bodyBytes,
      filename: _filenameFrom(claim.name, mime),
      mimeType: mime,
    );
  }

  // ---- Helpers -------------------------------------------------------------

  /// PostgREST reports a missing table/RPC as PGRST202/PGRST205 - used to tell
  /// "backend not deployed" apart from a genuine rejection.
  bool _isMissingBackend(PostgrestException e) {
    if (e.code == 'PGRST202' || e.code == 'PGRST205') return true;
    final m = e.message.toLowerCase();
    return m.contains('could not find the function') ||
        m.contains('create_view_once_share') ||
        m.contains('view_once_shares');
  }

  String _filenameFrom(String name, String mime) {
    final base = name.replaceAll(RegExp(r'[\\/:*?"<>|\r\n]'), '_').trim();
    final safe = base.isEmpty ? 'document' : base;
    if (RegExp(r'\.[A-Za-z0-9]{1,5}$').hasMatch(safe)) return safe;
    if (mime.contains('pdf')) return '$safe.pdf';
    if (mime.contains('png')) return '$safe.png';
    if (mime.contains('jpeg') || mime.contains('jpg')) return '$safe.jpg';
    if (mime.contains('webp')) return '$safe.webp';
    if (mime.contains('heic')) return '$safe.heic';
    return safe;
  }

  static String _short(String token) =>
      token.length <= 6 ? token : '${token.substring(0, 6)}…';
}
