import 'dart:typed_data';

import '../config/share_config.dart';

/// Recipient-facing outcome of a one-time link, as reported by the `share` Edge
/// Function's view-once API.
///
/// [ready] is the ONLY state in which the document can still be opened - and
/// even then, opening it burns the link. Everything else is terminal.
enum ViewOnceStatus {
  /// Not opened yet, not expired, not revoked - one view remains.
  ready,

  /// Already opened. Permanently dead, by design.
  viewed,

  /// The optional expiry lapsed before anyone opened it.
  expired,

  /// The sender killed the link before it was opened.
  revoked,

  /// No such token (or the underlying document is gone).
  notFound,

  /// The request itself failed (network / server).
  error,
}

extension ViewOnceStatusX on ViewOnceStatus {
  /// True only when a view is still available.
  bool get isReady => this == ViewOnceStatus.ready;

  /// True for every state that means "this link will never open again".
  bool get isSpent =>
      this == ViewOnceStatus.viewed ||
      this == ViewOnceStatus.expired ||
      this == ViewOnceStatus.revoked ||
      this == ViewOnceStatus.notFound;
}

ViewOnceStatus viewOnceStatusFrom(String? raw) {
  switch (raw) {
    case 'ready':
    case 'claimed':
      return ViewOnceStatus.ready;
    case 'viewed':
      return ViewOnceStatus.viewed;
    case 'expired':
      return ViewOnceStatus.expired;
    case 'revoked':
      return ViewOnceStatus.revoked;
    case 'not_found':
      return ViewOnceStatus.notFound;
    default:
      return ViewOnceStatus.error;
  }
}

/// How a shared file should be rendered. Mirrors the Edge Function's `kind`.
enum ViewOnceKind { image, pdf, other }

ViewOnceKind viewOnceKindFrom(String? raw) {
  switch (raw) {
    case 'image':
      return ViewOnceKind.image;
    case 'pdf':
      return ViewOnceKind.pdf;
    default:
      return ViewOnceKind.other;
  }
}

/// A one-time share the SENDER created. Mirrors one `view_once_shares` row.
///
/// Storage is reused: this points at an existing `documents` row by id, so no
/// file is ever copied or duplicated for a view-once link.
class ViewOnceShare {
  const ViewOnceShare({
    required this.id,
    required this.token,
    required this.documentId,
    required this.ownerId,
    required this.expiryTime,
    required this.viewed,
    required this.revoked,
    required this.createdAt,
    this.viewedAt,
  });

  final String id;

  /// The unguessable 32-hex public handle embedded in the link/QR. Generated by
  /// Postgres (a random UUID with the dashes stripped) - never by the client.
  final String token;
  final String documentId;
  final String ownerId;
  final DateTime expiryTime;
  final bool viewed;
  final bool revoked;
  final DateTime createdAt;
  final DateTime? viewedAt;

  /// The public URL encoded in the QR / handed to the recipient.
  String get url => ShareConfig.viewOncePublicUrl(token);

  /// True while the link can still be opened exactly once.
  bool get isLive => !viewed && !revoked && expiryTime.isAfter(DateTime.now());

  /// The sender-side status, honouring the wall clock.
  ViewOnceStatus get status {
    if (revoked) return ViewOnceStatus.revoked;
    if (viewed) return ViewOnceStatus.viewed;
    if (expiryTime.isBefore(DateTime.now())) return ViewOnceStatus.expired;
    return ViewOnceStatus.ready;
  }

  ViewOnceShare copyWith({bool? viewed, bool? revoked, DateTime? viewedAt}) {
    return ViewOnceShare(
      id: id,
      token: token,
      documentId: documentId,
      ownerId: ownerId,
      expiryTime: expiryTime,
      viewed: viewed ?? this.viewed,
      revoked: revoked ?? this.revoked,
      createdAt: createdAt,
      viewedAt: viewedAt ?? this.viewedAt,
    );
  }

  factory ViewOnceShare.fromMap(Map<String, dynamic> map) {
    return ViewOnceShare(
      id: map['id'] as String,
      token: map['token'] as String,
      documentId: map['document_id'] as String,
      ownerId: map['owner_id'] as String,
      expiryTime: DateTime.parse(map['expiry_time'] as String),
      viewed: (map['viewed'] as bool?) ?? false,
      revoked: (map['revoked'] as bool?) ?? false,
      createdAt: DateTime.parse(map['created_at'] as String),
      viewedAt: map['viewed_at'] == null
          ? null
          : DateTime.parse(map['viewed_at'] as String),
    );
  }
}

/// The result of a NON-CONSUMING status check on a one-time link.
///
/// Peeking never burns the share - only [ViewOnceClaim] does. That is what lets
/// the viewer show "ready to open" and warn the recipient before they spend
/// their single view.
class ViewOncePeek {
  const ViewOncePeek({
    required this.status,
    this.name = 'Document',
    this.type = 'Document',
    this.expiresAt,
    this.message,
  });

  final ViewOnceStatus status;
  final String name;
  final String type;
  final DateTime? expiresAt;
  final String? message;

  factory ViewOncePeek.fromJson(Map<String, dynamic> json) => ViewOncePeek(
        status: viewOnceStatusFrom(json['status'] as String?),
        name: _text(json['name'], 'Document'),
        type: _text(json['type'], 'Document'),
        expiresAt: json['expiresAt'] == null
            ? null
            : DateTime.tryParse(json['expiresAt'] as String),
        message: json['message'] as String?,
      );

  static const ViewOncePeek errored = ViewOncePeek(status: ViewOnceStatus.error);
}

/// A SUCCESSFUL claim: the link is now burned, and [accessKey] is the
/// short-lived grant that lets this one client fetch the bytes it just earned.
class ViewOnceClaim {
  const ViewOnceClaim({
    required this.accessKey,
    required this.name,
    required this.type,
    required this.kind,
    required this.mime,
    this.accessExpiresAt,
  });

  final String accessKey;
  final String name;
  final String type;
  final ViewOnceKind kind;
  final String mime;

  /// When the access key stops working (minutes, not hours).
  final DateTime? accessExpiresAt;

  factory ViewOnceClaim.fromJson(Map<String, dynamic> json) => ViewOnceClaim(
        accessKey: json['accessKey'] as String? ?? '',
        name: _text(json['name'], 'Document'),
        type: _text(json['type'], 'Document'),
        kind: viewOnceKindFrom(json['kind'] as String?),
        mime: json['mime'] as String? ?? 'application/octet-stream',
        accessExpiresAt: json['accessExpiresAt'] == null
            ? null
            : DateTime.tryParse(json['accessExpiresAt'] as String),
      );
}

/// Either a burned-and-opened document, or the reason it can't be opened.
class ViewOnceResult {
  const ViewOnceResult.claimed(this.claim)
      : status = ViewOnceStatus.ready,
        message = null;
  const ViewOnceResult.denied(this.status, {this.message}) : claim = null;

  final ViewOnceStatus status;
  final ViewOnceClaim? claim;
  final String? message;

  bool get isClaimed => claim != null;
}

/// The bytes of a one-time document, held in memory only.
///
/// Deliberately not a file path: for a view-once document the app renders from
/// memory wherever it can, so nothing is left behind on disk.
class ViewOnceFile {
  const ViewOnceFile({
    required this.bytes,
    required this.filename,
    required this.mimeType,
  });

  final Uint8List bytes;
  final String filename;
  final String mimeType;
}

String _text(Object? value, String fallback) {
  final s = value?.toString().trim();
  return (s == null || s.isEmpty) ? fallback : s;
}
