// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy7IKv7IjI130Od9mVNdAyijNRFM6w5gU',
    appId: '1:205011674878:web:5b40bfd86e7ec9a39a67af',
    messagingSenderId: '205011674878',
    projectId: 'inoapp-b0101',
    authDomain: 'inoapp-b0101.firebaseapp.com',
    storageBucket: 'inoapp-b0101.firebasestorage.app',
    measurementId: 'G-WTYXB6407E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanpIlktQphaJVi1ismWPVwslJ6L7RxUw',
    appId: '1:205011674878:android:f765ea1cb02cdee19a67af',
    messagingSenderId: '205011674878',
    projectId: 'inoapp-b0101',
    storageBucket: 'inoapp-b0101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Uhyz9gQO71elpCdf_2F4ldDCkK2nARI',
    appId: '1:205011674878:ios:ae329a4d4f44ee039a67af',
    messagingSenderId: '205011674878',
    projectId: 'inoapp-b0101',
    storageBucket: 'inoapp-b0101.firebasestorage.app',
    iosBundleId: 'com.ino.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy7IKv7IjI130Od9mVNdAyijNRFM6w5gU',
    appId: '1:205011674878:web:79a977048c6e75b69a67af',
    messagingSenderId: '205011674878',
    projectId: 'inoapp-b0101',
    authDomain: 'inoapp-b0101.firebaseapp.com',
    storageBucket: 'inoapp-b0101.firebasestorage.app',
    measurementId: 'G-EEQ15HP2WH',
  );
}
